.PHONY: clean All

All:
	@echo "----------Building project:[ 07_String - Debug ]----------"
	@cd "07_String" && "$(MAKE)" -f  "07_String.mk"
clean:
	@echo "----------Cleaning project:[ 07_String - Debug ]----------"
	@cd "07_String" && "$(MAKE)" -f  "07_String.mk" clean
